### PR TITLE
fix build failure with GHC 9.4

### PR DESCRIPTION
**Pull request by hsenag**

### CODE REVIEW

**Review by tvh — APPROVED** [review]

**Comment by ocharles** [comment]
@tvh Would you mind cutting a new Hackage release with this PR?

**Comment by ocharles** [comment]
@tvh Anything I can do to help get a new Hackage release? Sorry to nag!

**Comment by ocharles** [comment]
@tvh Just another little nudge to release this to Hackage. I'm more than happy to help maintain this library if that would help. Thanks!

**Comment by tvh** [comment]
Done.

**Comment by ocharles** [comment]
Many thanks!

**Pull request merged**
